name: Update Farming Widget

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run Widget Updater
        run: node farming-widget.js
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}
          PLAYER_UUID: ${{ secrets.PLAYER_UUID }}
          PROFILE_UUID: ${{ secrets.PROFILE_UUID }}
